### ISSUE TITLE
Support PHP 7

### ISSUE THREAD

**Issue by kyleatblackfoot** [helen/admin-color-schemer#24]
Hey guys, any plans to update this to PHP7?

**Comment by markjaquith** [comment]
What specifically isn’t working in PHP 7?

**Comment by KZeni** [comment]
It appears that the https://github.com/helen/admin-color-schemer/pull/21 issue (also see https://wordpress.org/support/topic/not-compairable-with-php-7-0/ and https://github.com/helen/admin-color-schemer/issues/19) was addressed here on GitHub, whereas it then wasn't fully propagated out to https://wordpress.org/plugins/admin-color-schemer/ (version number wasn't increased at the time, it doesn't include the updated/fixed version of phpsass, etc.)

Are you using the version from WP.org, @kyleatblackfoot? If so, does the problem go away after grabbing the current copy from here at GitHub? The WP.org repo really should address this simple remaining step causing this already resolved issue to linger for the WP.org user-base.

**Comment by c266** [comment]
I had to take it here too. Still not fixed on wordpress.org

**Comment by helen** [comment]
This is now released on WordPress.org!
